/* FinTrack V2 — no build tool. Replace firebaseConfig before deployment. */
const firebaseConfig = {
  apiKey: "AIzaSyDFW0RiRVL-nB3DR70luGAR-yA9C8Vhz-A",
  authDomain: "expense-tracking-796f2.firebaseapp.com",
  projectId: "expense-tracking-796f2",
  storageBucket: "expense-tracking-796f2.firebasestorage.app",
  messagingSenderId: "254010893537",
  appId: "1:254010893537:web:6c5a2296d733518e3d83a0",
  measurementId: "G-JF8M3XRCT3"
};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore(),storage=firebase.storage();
const FV={uid:null,user:null,tx:[],accounts:[],categories:[],tags:[],budgets:[],goals:[],recurring:[],settings:{},calDate:new Date(),editingId:null};
const $=id=>document.getElementById(id),fmt=n=>'฿'+Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2}),ymd=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`},monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
const coll=(name)=>db.collection('users').doc(FV.uid).collection(name),docRef=(name,id)=>coll(name).doc(id);
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2400)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function setOnline(){const e=$('syncState');const online=navigator.onLine;e.textContent=online?'ออนไลน์':'ออฟไลน์';e.classList.toggle('online',online);e.classList.toggle('offline',!online)}
window.addEventListener('online',setOnline);window.addEventListener('offline',setOnline);setOnline();
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+name));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===name)); if(name==='home')renderHome(); if(name==='transactions')renderTransactions(); if(name==='calendar')renderCalendar(); if(name==='reports')renderReports(); if(name==='budgets')renderBudgets()}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
function modal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.remove('hidden')};$('modalClose').onclick=()=>$('modal').classList.add('hidden');$('modal').addEventListener('click',e=>{if(e.target.id==='modal')$('modal').classList.add('hidden')});
function moneySum(type,month){return FV.tx.filter(t=>(t.type===type)&&(!month||t.date.startsWith(month))).reduce((s,t)=>s+Number(t.amount||0),0)}
function seedCategories(){return[{id:'food',name:'อาหาร',icon:'🍜',color:'#f97316'},{id:'coffee',name:'กาแฟ',icon:'☕',color:'#a16207',parent:'food'},{id:'transport',name:'เดินทาง',icon:'🚗',color:'#2563eb'},{id:'bills',name:'บิล/ค่าสาธารณูปโภค',icon:'💡',color:'#eab308'},{id:'shopping',name:'ช้อปปิ้ง',icon:'🛍️',color:'#db2777'},{id:'health',name:'สุขภาพ',icon:'❤️',color:'#ef4444'},{id:'salary',name:'เงินเดือน',icon:'💼',color:'#16a34a'},{id:'other',name:'อื่น ๆ',icon:'📌',color:'#6b7280'}]}
async function ensureSeed(){const snap=await coll('categories').limit(1).get();if(snap.empty){const batch=db.batch();seedCategories().forEach(x=>batch.set(coll('categories').doc(x.id),x));await batch.commit()}if(!(await coll('accounts').limit(1).get()).empty)return;await coll('accounts').add({name:'เงินสด',type:'cash',icon:'💵',opening:0,balance:0,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function loadAll(){const names=['transactions','accounts','categories','tags','budgets','goals','recurring'];const snaps=await Promise.all(names.map(n=>coll(n).orderBy('createdAt','desc').limit(1000).get().catch(()=>coll(n).limit(1000).get())));names.forEach((n,i)=>FV[n]=snaps[i].docs.map(d=>({id:d.id,...d.data()})));const s=await docRef('settings','main').get();FV.settings=s.exists?s.data():{};applySettings();renderAll();}
function applySettings(){const dark=FV.settings.theme==='dark'||(FV.settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',!!dark);$('darkToggle').checked=FV.settings.theme==='dark';}
function renderAll(){renderHome();renderTransactions();renderCalendar();renderReports();renderBudgets();updateUser()}
function renderHome(){const inc=moneySum('income',monthKey(new Date())),exp=moneySum('expense',monthKey(new Date()));$('balance').textContent=fmt(FV.accounts.reduce((s,a)=>s+Number(a.balance||0),0));$('monthIncome').textContent=fmt(inc);$('monthExpense').textContent=fmt(exp);$('saveRate').textContent=inc?Math.round((inc-exp)/inc*100)+'%':'0%';$('helloName').textContent='สวัสดี '+(FV.user?.displayName||FV.user?.email?.split('@')[0]||'');$('accounts').innerHTML=FV.accounts.map(a=>`<div class="account-card"><div class="account-icon">${esc(a.icon||'💳')}</div><div><b>${esc(a.name)}</b><span>${fmt(a.balance)}</span></div></div>`).join('')||'<div class="muted">ยังไม่มีบัญชี</div>';const arr=FV.tx.filter(t=>t.type!=='transfer').slice(0,7);$('recentTransactions').innerHTML=arr.map(txHtml).join('')||'<div class="muted">ยังไม่มีรายการ</div>'}
function catName(id){return FV.categories.find(c=>c.id===id)?.name||'-'}function accName(id){return FV.accounts.find(a=>a.id===id)?.name||'-'}
function txHtml(t){const sign=t.type==='income'?'+':t.type==='expense'?'-':'↔';return `<div class="tx-row" data-id="${t.id}" onclick="editTx('${t.id}')"><div class="tx-main"><div class="tx-icon">${esc(FV.categories.find(c=>c.id===t.categoryId)?.icon||'💰')}</div><div style="min-width:0"><div class="tx-name">${esc(t.note||catName(t.categoryId)||t.type)}</div><div class="tx-meta">${esc(t.date)} · ${esc(catName(t.categoryId))}${t.accountId?' · '+esc(accName(t.accountId)):''}</div></div></div><div class="amount ${t.type}">${sign}${fmt(t.amount).replace('฿','฿')}</div></div>`}
function renderTransactions(){let a=[...FV.tx];const q=$('searchTx').value.toLowerCase(),type=$('filterType').value,m=$('filterMonth').value;if(q)a=a.filter(t=>(t.note||'').toLowerCase().includes(q)||catName(t.categoryId).toLowerCase().includes(q)||(t.tags||[]).some(x=>x.toLowerCase().includes(q)));if(type!=='all')a=a.filter(t=>t.type===type);if(m)a=a.filter(t=>t.date.startsWith(m));$('transactionsList').innerHTML=a.map(txHtml).join('')||'<div class="muted">ไม่พบรายการ</div>'}
['searchTx','filterType','filterMonth'].forEach(id=>$(id).addEventListener('input',renderTransactions));
function accountOptions(selected=''){return FV.accounts.map(a=>`<option value="${a.id}" ${a.id===selected?'selected':''}>${esc(a.icon||'💳')} ${esc(a.name)}</option>`).join('')}
function categoryOptions(selected=''){return FV.categories.filter(c=>!c.parent).map(c=>`<optgroup label="${esc(c.name)}"><option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>${FV.categories.filter(s=>s.parent===c.id).map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>↳ ${esc(s.name)}</option>`).join('')}</optgroup>`).join('')}
window.editTx=async id=>{const t=FV.tx.find(x=>x.id===id);if(!t)return;modal('แก้ไขรายการ',txForm(t));document.querySelector('#txForm').onsubmit=e=>saveTx(e,id)};
function txForm(t={type:'expense',amount:'',date:ymd(new Date()),categoryId:FV.categories[0]?.id||'',accountId:FV.accounts[0]?.id||'',tags:[],note:'',transferTo:''}){return `<form id="txForm" class="form-grid"><label>ประเภท<select id="txType"><option value="expense" ${t.type==='expense'?'selected':''}>รายจ่าย</option><option value="income" ${t.type==='income'?'selected':''}>รายรับ</option><option value="transfer" ${t.type==='transfer'?'selected':''}>โอนเงิน</option></select></label><label>จำนวนเงิน<input id="txAmount" type="number" step="0.01" required value="${t.amount||''}"></label><label>วันที่<input id="txDate" type="date" required value="${t.date||ymd(new Date())}"></label><label>บัญชี<select id="txAccount">${accountOptions(t.accountId)}</select></label><label id="transferWrap" class="hidden">โอนไปบัญชี<select id="txTransferTo">${accountOptions(t.transferTo)}</select></label><label id="catWrap">หมวดหมู่<select id="txCategory">${categoryOptions(t.categoryId)}</select></label><label>หมายเหตุ<input id="txNote" value="${esc(t.note||'')}"></label><label>แท็ก (คั่นด้วย comma)<input id="txTags" value="${esc((t.tags||[]).join(', '))}"></label><label>แนบสลิป<input id="receipt" type="file" accept="image/*"></label><div id="ocrHint" class="muted small">อัปโหลดรูปได้ และใช้ OCR ช่วยอ่านยอดเงิน</div><div class="form-actions"><button class="secondary" type="button" onclick="$('modal').classList.add('hidden')">ยกเลิก</button><button class="primary" type="submit">บันทึก</button></div></form>`}
$('quickAdd').onclick=()=>{modal('เพิ่มรายการ',txForm());document.querySelector('#txForm').onsubmit=e=>saveTx(e);bindTxType();document.querySelector('#receipt').onchange=runOCR};
function bindTxType(){const f=()=>{const tr=$('txType').value==='transfer';$('transferWrap').classList.toggle('hidden',!tr);$('catWrap').classList.toggle('hidden',tr)};$('txType').onchange=f;f()}
async function runOCR(e){const file=e.target.files?.[0];if(!file)return;toast('กำลังอ่านสลิป...');try{const r=await Tesseract.recognize(file,'tha+eng');const txt=r.data.text||'';const m=txt.match(/(?:฿|THB|บาท)?\s*([0-9]{1,3}(?:[,.][0-9]{3})*(?:\.[0-9]{1,2})?)/g)||[];const cand=m.map(x=>parseFloat(x.replace(/[^0-9.]/g,''))).filter(n=>n>0&&n<1000000);if(cand.length){$('txAmount').value=Math.max(...cand).toFixed(2)}$('ocrHint').textContent='OCR อ่านข้อความแล้ว กรุณาตรวจสอบยอด/วันที่ก่อนบันทึก';toast('อ่านสลิปเสร็จแล้ว')}catch(err){$('ocrHint').textContent='OCR ไม่สำเร็จ กรุณากรอกเอง';toast('OCR ไม่สำเร็จ')}}
async function uploadReceipt(file,txId){if(!file)return null;const ref=storage.ref(`users/${FV.uid}/receipts/${txId}-${Date.now()}-${file.name}`);await ref.put(file);return ref.getDownloadURL()}
async function saveTx(e,id=null){e.preventDefault();const type=$('txType').value,amount=Number($('txAmount').value),accountId=$('txAccount').value,date=$('txDate').value;if(!(amount>0)||!accountId||!date)return toast('กรุณากรอกข้อมูลให้ครบ');const old=id?FV.tx.find(x=>x.id===id):null;const tx={type,amount,date,accountId,note:$('txNote').value.trim(),tags:$('txTags').value.split(',').map(x=>x.trim()).filter(Boolean),categoryId:type==='transfer'?null:$('txCategory').value,transferTo:type==='transfer'?$('txTransferTo').value:null,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),createdAt:old?.createdAt||firebase.firestore.FieldValue.serverTimestamp()};if(id){await docRef('transactions',id).set(tx,{merge:true})}else{const ref=await coll('transactions').add(tx);const file=$('receipt').files?.[0];if(file){const url=await uploadReceipt(file,ref.id);await ref.set({receiptUrl:url},{merge:true})}}await loadAll();$('modal').classList.add('hidden');toast(id?'แก้ไขรายการแล้ว':'บันทึกรายการแล้ว');}
$('addAccount').onclick=()=>showAccountModal();$('manageAccounts').onclick=()=>showAccountManager();
function showAccountModal(a={}){modal(a.id?'แก้ไขบัญชี':'เพิ่มบัญชี',`<form id="accountForm" class="form-grid"><label>ชื่อบัญชี<input id="aName" required value="${esc(a.name||'')}" placeholder="เช่น KBank, เงินสด"></label><label>ประเภท<select id="aType"><option value="cash">เงินสด</option><option value="bank">ธนาคาร</option><option value="wallet">e-Wallet</option><option value="card">บัตรเครดิต</option></select></label><label>ไอคอน<input id="aIcon" value="${esc(a.icon||'💳')}"></label><label>ยอดตั้งต้น<input id="aOpening" type="number" step="0.01" value="${a.opening||0}"></label><div class="form-actions"><button type="button" class="secondary" onclick="$('modal').classList.add('hidden')">ยกเลิก</button><button class="primary">บันทึก</button></div></form>`);$('accountForm').onsubmit=async e=>{e.preventDefault();const data={name:$('aName').value.trim(),type:$('aType').value,icon:$('aIcon').value,opening:Number($('aOpening').value||0),createdAt:a.createdAt||firebase.firestore.FieldValue.serverTimestamp()};if(a.id)await docRef('accounts',a.id).set(data,{merge:true});else await coll('accounts').add({...data,balance:data.opening});await loadAll();$('modal').classList.add('hidden')};}
function showAccountManager(){modal('จัดการบัญชี',`${FV.accounts.map(a=>`<div class="tx-row"><div><b>${esc(a.icon||'💳')} ${esc(a.name)}</b><div class="muted small">ยอด ${fmt(a.balance)}</div></div><button class="secondary" onclick="showAccountModal(FV.accounts.find(x=>x.id==='${a.id}'))">แก้ไข</button></div>`).join('')}<button class="primary" style="margin-top:10px;width:100%" onclick="showAccountModal()">+ เพิ่มบัญชี</button>`)}
async function syncAccountBalances(){const sums={};FV.tx.forEach(t=>{if(t.type==='income')sums[t.accountId]=(sums[t.accountId]||0)+Number(t.amount);if(t.type==='expense')sums[t.accountId]=(sums[t.accountId]||0)-Number(t.amount);if(t.type==='transfer'){sums[t.accountId]=(sums[t.accountId]||0)-Number(t.amount);sums[t.transferTo]=(sums[t.transferTo]||0)+Number(t.amount)}});for(const a of FV.accounts){const b=Number(a.opening||0)+(sums[a.id]||0);if(Math.abs(Number(a.balance||0)-b)>0.0001)await docRef('accounts',a.id).set({balance:b,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}}
function renderCalendar(){const d=FV.calDate,y=d.getFullYear(),m=d.getMonth();$('calTitle').textContent=d.toLocaleDateString('th-TH',{month:'long',year:'numeric'});const first=new Date(y,m,1),last=new Date(y,m+1,0),start=first.getDay(),total=last.getDate();let h='';for(let i=0;i<start;i++)h+='<div class="day other"></div>';for(let day=1;day<=total;day++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const ts=FV.tx.filter(t=>t.date===key);const net=ts.reduce((s,t)=>s+(t.type==='income'?t.amount:t.type==='expense'?-t.amount:0),0);h+=`<div class="day ${key===ymd(new Date())?'today':''}" onclick="dayClick('${key}')"><b>${day}</b><div class="dotline">${net?fmt(net):''}</div></div>`}$('calendarGrid').innerHTML=h}
window.dayClick=key=>{const ts=FV.tx.filter(t=>t.date===key);$('daySummary').classList.remove('hidden');$('daySummary').innerHTML=`<div class="split"><b>${key}</b><span>${fmt(ts.reduce((s,t)=>s+(t.type==='income'?t.amount:t.type==='expense'?-t.amount:0),0))}</span></div><div class="list" style="margin-top:8px">${ts.map(txHtml).join('')||'<span class="muted">ไม่มีรายการ</span>'}</div>`};$('prevMonth').onclick=()=>{FV.calDate.setMonth(FV.calDate.getMonth()-1);renderCalendar()};$('nextMonth').onclick=()=>{FV.calDate.setMonth(FV.calDate.getMonth()+1);renderCalendar()};
function renderReports(){const n=Number($('reportPeriod').value||12),end=new Date(),months=[];for(let i=n-1;i>=0;i--){const d=new Date(end.getFullYear(),end.getMonth()-i,1);months.push(monthKey(d))}const inc=months.map(m=>moneySum('income',m)),exp=months.map(m=>moneySum('expense',m));drawChart($('incomeExpenseChart'),months.map(m=>m.slice(2)),[{name:'รับ',data:inc},{name:'จ่าย',data:exp}],true);const cm=monthKey(new Date()),map={};FV.tx.filter(t=>t.type==='expense'&&t.date.startsWith(cm)).forEach(t=>map[catName(t.categoryId)]=(map[catName(t.categoryId)]||0)+Number(t.amount));const top=Object.entries(map).sort((a,b)=>b[1]-a[1]);drawPie($('categoryChart'),top);$('topCategories').innerHTML=top.slice(0,8).map(x=>`<div class="tx-row"><span>${esc(x[0])}</span><b>${fmt(x[1])}</b></div>`).join('')||'<div class="muted">ยังไม่มีข้อมูลเดือนนี้</div>'}
$('reportPeriod').onchange=renderReports;
function drawChart(c,labels,sets){const ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.clearRect(0,0,w,h);const max=Math.max(...sets.flatMap(s=>s.data),1),pad=28*devicePixelRatio;ctx.font=`${11*devicePixelRatio}px system-ui`;labels.forEach((l,i)=>{const x=pad+i*((w-pad*1.5)/(Math.max(labels.length-1,1)));sets.forEach((s,j)=>{const yy=h-pad-(s.data[i]/max)*(h-pad*2);ctx.fillStyle=j?'#ef4444':'#22c55e';ctx.beginPath();ctx.arc(x+(j-.5)*5*devicePixelRatio,yy,4*devicePixelRatio,0,Math.PI*2);ctx.fill()});ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.fillText(l,x-10*devicePixelRatio,h-6*devicePixelRatio)});[...Array(sets.length)].forEach((_,j)=>{ctx.fillStyle=j?'#ef4444':'#22c55e';ctx.fillRect(pad+j*90*devicePixelRatio,5,10*devicePixelRatio,10*devicePixelRatio);ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--text');ctx.fillText(sets[j].name,pad+15*devicePixelRatio+j*90*devicePixelRatio,14*devicePixelRatio)})}
function drawPie(c,items){const ctx=c.getContext('2d');const w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.clearRect(0,0,w,h);const total=items.reduce((s,x)=>s+x[1],0);if(!total){ctx.fillStyle='#94a3b8';ctx.fillText('ไม่มีข้อมูล',20,30);return}let a=-Math.PI/2,cx=w*.34,cy=h*.52,r=Math.min(w,h)*.3;items.slice(0,8).forEach((x,i)=>{const ang=x[1]/total*Math.PI*2;ctx.fillStyle=`hsl(${i*45},70%,55%)`;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,a+ang);ctx.closePath();ctx.fill();a+=ang});ctx.font=`${12*devicePixelRatio}px system-ui`;items.slice(0,8).forEach((x,i)=>{ctx.fillStyle=`hsl(${i*45},70%,55%)`;ctx.fillRect(w*.68,(20+i*20)*devicePixelRatio,10*devicePixelRatio,10*devicePixelRatio);ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--text');ctx.fillText(`${x[0]} ${Math.round(x[1]/total*100)}%`,w*.68+16*devicePixelRatio,(30+i*20)*devicePixelRatio)})}
function budgetForm(b={}){return `<form id="budgetForm" class="form-grid"><label>หมวดหมู่<select id="bCat">${categoryOptions(b.categoryId)}</select></label><label>งบต่อเดือน<input id="bAmount" type="number" step="0.01" value="${b.amount||''}" required></label><label>เตือนเมื่อ (%)<input id="bAlert" type="number" value="${b.alert||80}"></label><div class="form-actions"><button type="button" class="secondary" onclick="$('modal').classList.add('hidden')">ยกเลิก</button><button class="primary">บันทึก</button></div></form>`}
$('addBudget').onclick=()=>{modal('เพิ่มงบประมาณ',budgetForm());$('budgetForm').onsubmit=saveBudget};async function saveBudget(e){e.preventDefault();await coll('budgets').add({categoryId:$('bCat').value,amount:Number($('bAmount').value),alert:Number($('bAlert').value||80),month:monthKey(new Date()),createdAt:firebase.firestore.FieldValue.serverTimestamp()});await loadAll();$('modal').classList.add('hidden')}
function renderBudgets(){const m=monthKey(new Date());$('budgets').innerHTML=FV.budgets.map(b=>{const used=FV.tx.filter(t=>t.type==='expense'&&t.date.startsWith(m)&&t.categoryId===b.categoryId).reduce((s,t)=>s+Number(t.amount),0),pct=Math.round(used/Number(b.amount||1)*100);return `<div class="card"><div class="split"><b>${esc(catName(b.categoryId))}</b><span>${fmt(used)} / ${fmt(b.amount)}</span></div><div class="progress" style="margin:9px 0"><span style="width:${Math.min(pct,100)}%"></span></div><div class="muted small">ใช้ไป ${pct}% · เตือนที่ ${b.alert||80}%</div></div>`}).join('')||'<div class="muted">ยังไม่มีงบประมาณ</div>';$('goals').innerHTML=FV.goals.map(g=>{const pct=Math.min(100,Math.round(Number(g.saved||0)/Number(g.target||1)*100));return `<div class="card"><div class="split"><b>${esc(g.name)}</b><span>${pct}%</span></div><div class="progress" style="margin:9px 0"><span style="width:${pct}%"></span></div><div class="muted small">${fmt(g.saved)} / ${fmt(g.target)}</div></div>`}).join('')||'<div class="muted">ยังไม่มีเป้าหมาย</div>'}
$('addGoal').onclick=()=>{modal('เพิ่มเป้าหมาย',`<form id="goalForm" class="form-grid"><label>ชื่อเป้าหมาย<input id="gName" required></label><label>เป้าหมายเงิน<input id="gTarget" type="number" required></label><label>ออมไปแล้ว<input id="gSaved" type="number" value="0"></label><div class="form-actions"><button type="button" class="secondary" onclick="$('modal').classList.add('hidden')">ยกเลิก</button><button class="primary">บันทึก</button></div></form>`);$('goalForm').onsubmit=async e=>{e.preventDefault();await coll('goals').add({name:$('gName').value,target:Number($('gTarget').value),saved:Number($('gSaved').value||0),createdAt:firebase.firestore.FieldValue.serverTimestamp()});await loadAll();$('modal').classList.add('hidden')};}
$('manageCategories').onclick=()=>{modal('หมวดหมู่',`<div class="list">${FV.categories.map(c=>`<div class="tx-row"><span>${esc(c.icon)} ${esc(c.name)}</span><button class="secondary" onclick="editCategory('${c.id}')">แก้ไข</button></div>`).join('')}</div><button class="primary" style="margin-top:10px;width:100%" onclick="editCategory()">+ เพิ่มหมวด</button>`)};
window.editCategory=id=>{const c=id?FV.categories.find(x=>x.id===id):{};modal(id?'แก้ไขหมวด':'เพิ่มหมวด',`<form id="catForm" class="form-grid"><label>ชื่อ<input id="cName" value="${esc(c.name||'')}" required></label><label>ไอคอน<input id="cIcon" value="${esc(c.icon||'📌')}"></label><label>สี<input id="cColor" value="${esc(c.color||'#6b7280')}"></label><label>หมวดหลัก<select id="cParent"><option value="">ไม่มี</option>${FV.categories.filter(x=>!x.parent&&x.id!==id).map(x=>`<option value="${x.id}" ${x.id===c.parent?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="form-actions"><button type="button" class="secondary" onclick="$('modal').classList.add('hidden')">ยกเลิก</button><button class="primary">บันทึก</button></div></form>`);$('catForm').onsubmit=async e=>{e.preventDefault();const data={name:$('cName').value.trim(),icon:$('cIcon').value,color:$('cColor').value,parent:$('cParent').value||null,createdAt:c.createdAt||firebase.firestore.FieldValue.serverTimestamp()};if(id)await docRef('categories',id).set(data,{merge:true});else await coll('categories').add(data);await loadAll();$('modal').classList.add('hidden')};}
$('manageTags').onclick=()=>{modal('แท็ก',`${FV.tags.map(t=>`<span class="chip">#${esc(t.name)}</span>`).join(' ')||'<span class="muted">ยังไม่มีแท็ก</span>'}<form id="tagForm" class="row" style="gap:8px;margin-top:12px"><input id="tagName" placeholder="เช่น ทริปญี่ปุ่น" class="grow"><button class="primary">เพิ่ม</button></form>`);$('tagForm').onsubmit=async e=>{e.preventDefault();const n=$('tagName').value.trim().replace(/^#/,'');if(!n)return;await coll('tags').add({name:n,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await loadAll();$('manageTags').click()}}
$('manageRecurring').onclick=()=>{modal('รายการประจำ',`<button class="primary" style="width:100%;margin-bottom:10px" onclick="showRecurringForm()">+ เพิ่มรายการประจำ</button><div class="list">${FV.recurring.map(r=>`<div class="tx-row"><div><b>${esc(r.note||catName(r.categoryId))}</b><div class="muted small">${r.frequency||'monthly'} · วันที่ ${r.day||1} · ${fmt(r.amount)}</div></div></div>`).join('')||'<div class="muted">ยังไม่มีรายการประจำ</div>'}</div>`)};
window.showRecurringForm=()=>{modal('เพิ่มรายการประจำ',`<form id="recForm" class="form-grid"><label>รายการ<input id="rNote" required></label><label>จำนวนเงิน<input id="rAmount" type="number" required></label><label>ประเภท<select id="rType"><option value="expense">รายจ่าย</option><option value="income">รายรับ</option></select></label><label>บัญชี<select id="rAccount">${accountOptions()}</select></label><label>หมวดหมู่<select id="rCat">${categoryOptions()}</select></label><label>ความถี่<select id="rFreq"><option value="monthly">รายเดือน</option><option value="weekly">รายสัปดาห์</option></select></label><label>วันของเดือน/สัปดาห์<input id="rDay" type="number" value="1"></label><div class="form-actions"><button type="button" class="secondary" onclick="$('modal').classList.add('hidden')">ยกเลิก</button><button class="primary">บันทึก</button></div></form>`);$('recForm').onsubmit=async e=>{e.preventDefault();await coll('recurring').add({note:$('rNote').value,amount:Number($('rAmount').value),type:$('rType').value,accountId:$('rAccount').value,categoryId:$('rCat').value,frequency:$('rFreq').value,day:Number($('rDay').value||1),lastRun:null,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await loadAll();$('modal').classList.add('hidden')}};
async function processRecurring(){const today=new Date();const key=ymd(today);for(const r of FV.recurring){const due=r.frequency==='weekly'?today.getDay()===Number(r.day||0):today.getDate()===Number(r.day||1);if(!due||r.lastRun===key)continue;await coll('transactions').add({type:r.type,amount:r.amount,date:key,note:r.note,accountId:r.accountId,categoryId:r.categoryId,tags:['recurring'],createdAt:firebase.firestore.FieldValue.serverTimestamp()});await docRef('recurring',r.id).set({lastRun:key},{merge:true})}}
$('backupData').onclick=()=>{const payload=JSON.stringify({version:2,exportedAt:new Date().toISOString(),transactions:FV.tx,accounts:FV.accounts,categories:FV.categories,tags:FV.tags,budgets:FV.budgets,goals:FV.goals,recurring:FV.recurring,settings:FV.settings});downloadBlob(payload,'fintrack-backup.json','application/json')};
$('importCsv').onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='.csv';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;const text=await f.text();const rows=text.split(/\r?\n/).filter(Boolean).map(x=>x.split(',').map(s=>s.replace(/^"|"$/g,'')));const headers=(rows.shift()||[]).map(x=>x.trim());let n=0;for(const row of rows){const o={};headers.forEach((h,i)=>o[h]=row[i]);if(!o.amount||!o.date)continue;await coll('transactions').add({type:o.type||'expense',amount:Number(o.amount),date:o.date,note:o.note||'',accountId:o.accountId||FV.accounts[0]?.id,categoryId:o.categoryId||FV.categories[0]?.id,tags:(o.tags||'').split('|').filter(Boolean),createdAt:firebase.firestore.FieldValue.serverTimestamp()});n++}await loadAll();toast(`นำเข้า ${n} รายการ`);};input.click()};
$('exportCsv').onclick=()=>{const headers=['date','type','amount','note','categoryId','accountId','tags'];const lines=[headers.join(',')];FV.tx.forEach(t=>lines.push(headers.map(k=>`"${String(k==='tags'?(t.tags||[]).join('|'):t[k]??'').replace(/"/g,'""')}"`).join(',')));downloadBlob('\ufeff'+lines.join('\n'),'fintrack-transactions.csv','text/csv;charset=utf-8')};
function downloadBlob(data,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('btnTheme').onclick=async()=>{const next=document.body.classList.contains('dark')?'light':'dark';await docRef('settings','main').set({theme:next},{merge:true});FV.settings.theme=next;applySettings()};$('darkToggle').onchange=async e=>{const theme=e.target.checked?'dark':'light';FV.settings.theme=theme;applySettings();await docRef('settings','main').set({theme},{merge:true})};
$('pinToggle').onchange=async e=>{if(e.target.checked){const p=prompt('ตั้ง PIN 4-6 หลัก');if(!/^\d{4,6}$/.test(p||'')){e.target.checked=false;return}localStorage.setItem('fintrack_pin_'+FV.uid,p);toast('ตั้ง PIN แล้ว')}else{localStorage.removeItem('fintrack_pin_'+FV.uid)}};
$('btnLock').onclick=()=>{if(localStorage.getItem('fintrack_pin_'+FV.uid)){$('lockScreen').classList.remove('hidden')}};$('unlockBtn').onclick=()=>{$('lockScreen').classList.add('hidden')};
$('btnProfile').onclick=()=>showProfile();function updateUser(){$('userInfo').textContent=FV.user?`${FV.user.displayName||''} · ${FV.user.email||''}`:''}
function showProfile(){modal('โปรไฟล์',`<div class="card"><b>${esc(FV.user?.displayName||'ผู้ใช้')}</b><p class="muted">${esc(FV.user?.email||'')}</p><button class="secondary" onclick="backupAll()">สำรองข้อมูล</button></div>`)}
window.backupAll=()=>$('backupData').click();
$('manageNotifications').onclick=async()=>{modal('การแจ้งเตือน',`<div class="card"><p>เปิด Push Notification เพื่อรับแจ้งเตือนจาก Firebase Cloud Messaging</p><button id="enablePush" class="primary">เปิดการแจ้งเตือน</button><p class="muted small">ต้องเปิดโดเมนใน HTTPS และใส่ Web Push VAPID key ใน app.js ก่อน</p></div>`);$('enablePush').onclick=enablePush};
async function enablePush(){try{if(!('Notification'in window))return toast('เบราว์เซอร์ไม่รองรับ');const permission=await Notification.requestPermission();if(permission!=='granted')return toast('ไม่ได้รับสิทธิ์แจ้งเตือน');if(!firebase.messaging.isSupported())return toast('ไม่รองรับ FCM บนเบราว์เซอร์นี้');const msg=firebase.messaging();const token=await msg.getToken({vapidKey:'YOUR_PUBLIC_VAPID_KEY',serviceWorkerRegistration:await navigator.serviceWorker.ready});await coll('devices').doc(btoa(token).slice(0,50)).set({token,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),ua:navigator.userAgent},{merge:true});toast('เปิดการแจ้งเตือนแล้ว')}catch(e){console.error(e);toast('เปิดแจ้งเตือนไม่สำเร็จ')}}
$('btnLogout').onclick=()=>auth.signOut();
$('btnLogin').onclick=async()=>{try{await auth.signInWithEmailAndPassword($('email').value,$('password').value)}catch(e){toast(e.message)}};$('btnRegister').onclick=async()=>{try{await auth.createUserWithEmailAndPassword($('email').value,$('password').value);toast('สมัครสำเร็จ')}catch(e){toast(e.message)}};$('btnGoogle').onclick=async()=>{try{await auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}catch(e){toast(e.message)}};
$('manageAccounts').addEventListener('click',showAccountManager);$('manageCategories').addEventListener('click',()=>{});
async function bootUser(user){FV.user=user;FV.uid=user.uid;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');await ensureSeed();await loadAll();await syncAccountBalances();await loadAll();await processRecurring();await loadAll();if(localStorage.getItem('fintrack_pin_'+FV.uid))toast('เปิด PIN Lock ได้จากเมนูตั้งค่า');registerSW()}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
auth.onAuthStateChanged(user=>{if(user)bootUser(user);else{$('authView').classList.remove('hidden');$('appView').classList.add('hidden');}});
