import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { initializeFirestore, persistentLocalCache, persistentMultipleTabManager, collection, doc, getDocs, getDoc, addDoc, setDoc, updateDoc, deleteDoc, query, orderBy, limit, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
import { getMessaging, getToken, onMessage, isSupported } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-messaging.js';

/* 1) ใส่ Firebase config ของคุณตรงนี้ */
const firebaseConfig = {
  apiKey: "AIzaSyDFW0RiRVL-nB3DR70luGAR-yA9C8Vhz-A",
  authDomain: "expense-tracking-796f2.firebaseapp.com",
  projectId: "expense-tracking-796f2",
  storageBucket: "expense-tracking-796f2.firebasestorage.app",
  messagingSenderId: "254010893537",
  appId: "1:254010893537:web:6c5a2296d733518e3d83a0",
  measurementId: "G-JF8M3XRCT3"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = initializeFirestore(app, { localCache: persistentLocalCache({ tabManager: persistentMultipleTabManager() }) });

const state = {
  user:null, tx:[], categories:[], tags:[], budgets:[], goals:[], recurring:[], settings:{}, txType:'expense', charts:{}, unsubscribe:[]
};
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const money = n => new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:2}).format(Number(n)||0);
const localDate = d => { const x=d?new Date(d):new Date(); return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10); };
const key = name => `fintrack_${state.user?.uid || 'guest'}_${name}`;
const showLoading=(on,text='กำลังโหลด…')=>{ $('#loading').classList.toggle('hidden',!on); $('#loadingText').textContent=text; };
const toast=(msg,type='ok')=>{ const el=document.createElement('div');el.textContent=msg;el.style.cssText=`position:fixed;left:50%;bottom:95px;transform:translateX(-50%);z-index:300;background:${type==='error'?'#991b1b':'#102021'};color:#fff;padding:11px 16px;border-radius:999px;box-shadow:0 8px 24px rgba(0,0,0,.2);font-size:.82rem`;document.body.appendChild(el);setTimeout(()=>el.remove(),2400); };

function userCol(name){return collection(db,'users',state.user.uid,name)}
function userDoc(name,id){return doc(db,'users',state.user.uid,name,id)}

async function ensureDefaults(){
  const defaults=[
    {name:'อาหาร',icon:'🍜',color:'#f97316',parentId:null},{name:'กาแฟ',icon:'☕',color:'#a16207',parentId:'อาหาร'},
    {name:'เดินทาง',icon:'🚗',color:'#2563eb',parentId:null},{name:'ช้อปปิ้ง',icon:'🛍️',color:'#7c3aed',parentId:null},
    {name:'บิล/สาธารณูปโภค',icon:'💡',color:'#0891b2',parentId:null},{name:'สุขภาพ',icon:'🩺',color:'#dc2626',parentId:null},
    {name:'เงินเดือน',icon:'💰',color:'#16a34a',parentId:null},{name:'อื่น ๆ',icon:'📦',color:'#64748b',parentId:null}
  ];
  const catSnap=await getDocs(query(userCol('categories'),limit(1))); if(catSnap.empty){for(const c of defaults) await addDoc(userCol('categories'),{...c,createdAt:serverTimestamp()});}
}

async function loadAll(){
  await ensureDefaults();
  const reads=['transactions','categories','tags','budgets','goals','recurring'];
  for(const name of reads){
    const q=query(userCol(name),orderBy(name==='transactions'?'date':'createdAt','desc'));
    const un=onSnapshot(q,snap=>{state[name]=snap.docs.map(d=>({id:d.id,...d.data()})); render();}); state.unsubscribe.push(un);
  }
  const settingsRef=userDoc('settings','main');
  const settingsSnap=await getDoc(settingsRef); state.settings=settingsSnap.exists()?settingsSnap.data():{};
  if(!settingsSnap.exists()) await setDoc(settingsRef,{currency:'THB',theme:'system',dailyReminderTime:'20:00',pinEnabled:false});
  $('#userEmailLabel').textContent=state.user.email||'-';
  $('#pinEnabled').checked=!!state.settings.pinEnabled; $('#dailyReminderTime').value=state.settings.dailyReminderTime||'20:00';
  await processRecurring();
}

function render(){ if(!state.user)return; renderHome();renderTransactions();renderReports();renderBudgetsGoals();renderSettings(); }
function filteredPeriod(period){const now=new Date(); return state.tx.filter(t=>{const d=new Date(t.date);if(period==='all')return true;if(period==='year')return d.getFullYear()===now.getFullYear();return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();});}
function totals(items){return items.reduce((a,t)=>{const v=Number(t.amount)||0;if(t.type==='income')a.income+=v;else a.expense+=v;return a},{income:0,expense:0});}
function renderHome(){const t=totals(filteredPeriod('month'));$('#balanceValue').textContent=money(t.income-t.expense);$('#incomeValue').textContent=money(t.income);$('#expenseValue').textContent=money(t.expense);const list=state.tx.slice(0,8);$('#recentList').innerHTML=list.length?list.map(txHtml).join(''):'<div class="panel muted">ยังไม่มีรายการ</div>';}
function txHtml(t){const c=state.categories.find(x=>x.name===t.category)||{};const sign=t.type==='income'?'+':'−';return `<button class="tx-item" data-edit-tx="${t.id}"><div class="tx-icon" style="background:${c.color||'#e2e8f0'}22">${c.icon||'💳'}</div><div class="tx-main"><div class="tx-title">${esc(t.title||t.category||'รายการ')}</div><div class="tx-meta">${fmtDate(t.date)} · ${esc(t.category||'')}</div></div><div class="tx-amt ${t.type==='income'?'income-text':'expense-text'}">${sign}${money(t.amount).replace('฿','฿')}</div></button>`;}
function renderTransactions(){const search=($('#txSearch')?.value||'').toLowerCase().trim();const type=$('#txTypeFilter')?.value||'all';const month=$('#txMonthFilter')?.value||'all';const items=state.tx.filter(t=>(type==='all'||t.type===type)&&(month==='all'||t.date?.slice(0,7)===month)&&( !search || `${t.title} ${t.category} ${(t.tags||[]).join(' ')} ${t.note||''}`.toLowerCase().includes(search)));$('#allTxList').innerHTML=items.length?items.map(txHtml).join(''):'<div class="panel muted">ไม่พบรายการ</div>';const months=[...new Set(state.tx.map(t=>t.date?.slice(0,7)).filter(Boolean))].sort().reverse();const sel=$('#txMonthFilter');if(sel){const current=sel.value;sel.innerHTML='<option value="all">ทุกเดือน</option>'+months.map(m=>`<option value="${m}">${m}</option>`).join('');if(months.includes(current))sel.value=current;}}
function renderReports(){const items=filteredPeriod($('#reportPeriod')?.value||'month');const t=totals(items);$('#reportIncome').textContent=money(t.income);$('#reportExpense').textContent=money(t.expense);$('#reportNet').textContent=money(t.income-t.expense);drawCharts(items);drawTrend();}
function destroyChart(name){if(state.charts[name]){state.charts[name].destroy();state.charts[name]=null;}}
function drawCharts(items){if(typeof Chart==='undefined')return;destroyChart('ie');destroyChart('cat');state.charts.ie=new Chart($('#incomeExpenseChart'),{type:'bar',data:{labels:['รายรับ','รายจ่าย'],datasets:[{data:[totals(items).income,totals(items).expense],borderRadius:10}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});const map={};items.filter(t=>t.type==='expense').forEach(t=>map[t.category]=(map[t.category]||0)+Number(t.amount||0));const labels=Object.keys(map);state.charts.cat=new Chart($('#categoryChart'),{type:'doughnut',data:{labels,datasets:[{data:labels.map(k=>map[k])}]},options:{plugins:{legend:{position:'bottom'}}}});}
function drawTrend(){const map={};state.tx.forEach(t=>{const k=(t.date||'').slice(0,7);if(!k)return;if(!map[k])map[k]={i:0,e:0};if(t.type==='income')map[k].i+=Number(t.amount||0);else map[k].e+=Number(t.amount||0);});const rows=Object.entries(map).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,12);$('#trendTable').innerHTML=`<table><thead><tr><th>เดือน</th><th>รายรับ</th><th>รายจ่าย</th><th>สุทธิ</th></tr></thead><tbody>${rows.map(([m,v])=>`<tr><td>${m}</td><td>${money(v.i)}</td><td>${money(v.e)}</td><td>${money(v.i-v.e)}</td></tr>`).join('')}</tbody></table>`;}
function renderBudgetsGoals(){const month=localDate().slice(0,7);$('#budgetList').innerHTML=state.budgets.length?state.budgets.map(b=>{const used=state.tx.filter(t=>t.type==='expense'&&t.date?.slice(0,7)===month&&t.category===b.category).reduce((a,t)=>a+Number(t.amount||0),0);const pct=Math.min(100,used/(Number(b.limit)||1)*100);return `<div class="budget-item"><div class="section-head"><span>${esc(b.category)}</span><span>${money(used)} / ${money(b.limit)}</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="tx-meta">${pct>=100?'เกินงบแล้ว':pct>=80?'ใช้ถึง 80%+':'อยู่ในงบ'} · <button class="text-btn" data-del-budget="${b.id}">ลบ</button></div></div>`;}).join(''):'<div class="muted">ยังไม่มีงบประมาณ</div>';
$('#goalList').innerHTML=state.goals.length?state.goals.map(g=>{const pct=Math.min(100,Number(g.target)?Number(g.saved||0)/Number(g.target)*100:0);return `<div class="goal-item"><div class="section-head"><span>${esc(g.name)}</span><span>${Math.round(pct)}%</span></div><div class="progress"><span style="width:${pct}%"></span></div><div class="tx-meta">${money(g.saved)} / ${money(g.target)} · <button class="text-btn" data-add-goal="${g.id}">เติมเงิน</button> · <button class="text-btn" data-del-goal="${g.id}">ลบ</button></div></div>`;}).join(''):'<div class="muted">ยังไม่มีเป้าหมาย</div>';
}
function renderSettings(){const top=state.categories.filter(c=>!c.parentId);$('#categoryList').innerHTML=top.map(c=>{const sub=state.categories.filter(s=>s.parentId===c.name);return `<div class="settings-row"><span>${c.icon} ${esc(c.name)} <small class="muted">${sub.length?`· ${sub.map(x=>x.name).join(', ')}`:''}</small></span><button class="text-btn" data-del-cat="${c.id}">ลบ</button></div>`}).join('');$('#tagList').innerHTML=state.tags.map(t=>`<button class="chip" data-del-tag="${t.id}">#${esc(t.name)} ✕</button>`).join('')||'<span class="muted">ยังไม่มีแท็ก</span>';}

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function fmtDate(s){if(!s)return '-';const d=new Date(s);return new Intl.DateTimeFormat('th-TH',{day:'2-digit',month:'short',year:'2-digit'}).format(d)}

function openPage(name){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+name+'Page').classList.add('active');$$('.nav-item[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});}
function fillCategoryOptions(){const sel=$('#txCategory');sel.innerHTML=state.categories.map(c=>`<option value="${esc(c.name)}">${c.parentId?'↳ ':''}${c.icon} ${esc(c.name)}</option>`).join('');}
function openTx(type='expense',tx=null){fillCategoryOptions();state.txType=type;$$('.type-toggle button').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('#txModalTitle').textContent=tx?'แก้ไขรายการ':'เพิ่มรายการ';$('#txId').value=tx?.id||'';$('#txAmount').value=tx?.amount||'';$('#txDate').value=tx?.date?.slice(0,10)||localDate();$('#txTime').value=tx?.time||new Date().toTimeString().slice(0,5);$('#txCategory').value=tx?.category||state.categories.find(c=>!c.parentId)?.name||'';$('#txTitle').value=tx?.title||'';$('#txTags').value=(tx?.tags||[]).map(t=>'#'+t).join(', ');$('#txNote').value=tx?.note||'';$('#deleteTxBtn').classList.toggle('hidden',!tx);$('#txModal').showModal();}
async function saveTx(e){e.preventDefault();const data={type:state.txType,amount:Number($('#txAmount').value),date:$('#txDate').value,time:$('#txTime').value,category:$('#txCategory').value,title:$('#txTitle').value.trim(),tags:$('#txTags').value.split(',').map(x=>x.trim().replace(/^#/,'')).filter(Boolean),note:$('#txNote').value.trim(),updatedAt:serverTimestamp()};const id=$('#txId').value;try{if(id)await updateDoc(userDoc('transactions',id),data);else await addDoc(userCol('transactions'),{...data,createdAt:serverTimestamp()});$('#txModal').close();toast('บันทึกรายการแล้ว');}catch(err){toast(err.message,'error');}}

async function processRecurring(){const today=localDate();for(const r of state.recurring){if(!r.active)continue;const last=r.lastRun||'';if(last===today)continue;const dueDay=Number(r.day||1);const d=new Date();if(d.getDate()===dueDay){await addDoc(userCol('transactions'),{type:r.type,amount:Number(r.amount),date:today,time:'08:00',category:r.category,title:r.title,tags:r.tags||[],note:`Recurring: ${r.id}`,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(userDoc('recurring',r.id),{lastRun:today,updatedAt:serverTimestamp()});}}}

async function openSimple(type){const title=$('#simpleTitle'),fields=$('#simpleFields');if(type==='category'){title.textContent='เพิ่มหมวดหมู่';fields.innerHTML=`<label>ชื่อหมวดหมู่<input name="name" required></label><label>ไอคอน<input name="icon" value="📦"></label><label>สี<input name="color" type="color" value="#0f766e"></label><label>เป็นหมวดย่อยของ<select name="parentId"><option value="">หมวดหลัก</option>${state.categories.filter(c=>!c.parentId).map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}</select></label>`;}else if(type==='tag'){title.textContent='เพิ่มแท็ก';fields.innerHTML=`<label>ชื่อแท็ก<input name="name" placeholder="ทริปญี่ปุ่น" required></label>`;}else if(type==='budget'){title.textContent='เพิ่มงบประมาณ';fields.innerHTML=`<label>หมวดหมู่<select name="category" required>${state.categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}</select></label><label>งบต่อเดือน<input name="limit" type="number" min="0" step="0.01" required></label><label>แจ้งเตือนเมื่อถึง %<input name="alertPct" type="number" value="80" min="1" max="100"></label>`;}else if(type==='goal'){title.textContent='เพิ่มเป้าหมาย';fields.innerHTML=`<label>ชื่อเป้าหมาย<input name="name" required placeholder="เงินสำรองฉุกเฉิน"></label><label>ยอดเป้าหมาย<input name="target" type="number" min="0" step="0.01" required></label><label>ยอดเริ่มต้น<input name="saved" type="number" min="0" step="0.01" value="0"></label>`;}else if(type==='recurring'){title.textContent='เพิ่มรายการประจำ';fields.innerHTML=`<label>ประเภท<select name="type"><option value="expense">รายจ่าย</option><option value="income">รายรับ</option></select></label><label>จำนวนเงิน<input name="amount" type="number" required></label><label>วันของเดือน<input name="day" type="number" min="1" max="28" value="1" required></label><label>หมวดหมู่<select name="category">${state.categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}</select></label><label>ชื่อรายการ<input name="title" required placeholder="ค่าเช่าบ้าน"></label>`;} $('#simpleForm').dataset.type=type;$('#simpleModal').showModal();}
async function saveSimple(e){e.preventDefault();const type=e.currentTarget.dataset.type;const form=new FormData(e.currentTarget);const v=Object.fromEntries(form.entries());try{if(type==='category')await addDoc(userCol('categories'),{name:v.name.trim(),icon:v.icon||'📦',color:v.color||'#0f766e',parentId:v.parentId||null,createdAt:serverTimestamp()});if(type==='tag')await addDoc(userCol('tags'),{name:v.name.trim().replace(/^#/ ,''),createdAt:serverTimestamp()});if(type==='budget')await addDoc(userCol('budgets'),{category:v.category,limit:Number(v.limit),alertPct:Number(v.alertPct||80),createdAt:serverTimestamp()});if(type==='goal')await addDoc(userCol('goals'),{name:v.name,target:Number(v.target),saved:Number(v.saved||0),createdAt:serverTimestamp()});if(type==='recurring')await addDoc(userCol('recurring'),{type:v.type,amount:Number(v.amount),day:Number(v.day),category:v.category,title:v.title,active:true,createdAt:serverTimestamp()});$('#simpleModal').close();toast('บันทึกแล้ว');}catch(err){toast(err.message,'error');}}

async function deleteTransaction(){const id=$('#txId').value;if(!id)return; if(!confirm('ลบรายการนี้หรือไม่?'))return;await deleteDoc(userDoc('transactions',id));$('#txModal').close();toast('ลบแล้ว');}

async function scanReceipt(file){$('#ocrStatus').textContent='กำลังประมวลผล OCR…';$('#runOcrBtn').disabled=true;const worker=await Tesseract.createWorker('eng');const {data}=await worker.recognize(file);await worker.terminate();const text=data.text||'';$('#txReceiptText').value=text;const nums=text.match(/(?:฿|THB|บาท)?\s*([0-9]{1,3}(?:[,][0-9]{3})*(?:\.[0-9]{1,2})?)/g)||[];const amount=nums.map(x=>Number(x.replace(/[^0-9.]/g,''))).filter(x=>x>0&&x<1000000).sort((a,b)=>b-a)[0]||'';$('#ocrStatus').textContent=text?`อ่านได้แล้ว: พบข้อความ ${text.length} ตัวอักษร${amount?` · ยอดที่คาดว่าเป็นจำนวนเงิน ${money(amount)}`:''}`:'ไม่พบข้อความ';$('#useOcrBtn').classList.remove('hidden');$('#useOcrBtn').dataset.amount=amount;$('#useOcrBtn').dataset.text=text;$('#runOcrBtn').disabled=false;}

async function enableNotifications(){if(!('Notification'in window)){toast('เบราว์เซอร์นี้ไม่รองรับ Notifications','error');return}const permission=await Notification.requestPermission();if(permission!=='granted'){toast('ไม่ได้รับอนุญาตแจ้งเตือน','error');return}try{if(await isSupported()){const messaging=getMessaging(app);const vapid='YOUR_PUBLIC_VAPID_KEY';if(vapid!=='YOUR_PUBLIC_VAPID_KEY'){const token=await getToken(messaging,{vapidKey:vapid});await setDoc(userDoc('devices',btoa(token).slice(0,80)),{token,updatedAt:serverTimestamp()});}toast('เปิดการแจ้งเตือนแล้ว');}}catch(e){toast('ต้องตั้งค่า FCM เพิ่มใน Firebase ก่อน','error');}}

async function setPin(){const p=prompt('ตั้ง PIN 4-6 หลัก');if(!p||!/^\d{4,6}$/.test(p)){toast('PIN ต้องเป็นตัวเลข 4-6 หลัก','error');return}localStorage.setItem(key('pin'),p);await updateDoc(userDoc('settings','main'),{pinEnabled:true});state.settings.pinEnabled=true;$('#pinEnabled').checked=true;toast('ตั้ง PIN แล้ว');}
function lockApp(){if(!state.settings.pinEnabled){toast('เปิด PIN Lock ก่อน','error');return}$('#lockView').classList.remove('hidden');$('#pinInput').value='';setTimeout(()=>$('#pinInput').focus(),100);}
function unlock(){const p=$('#pinInput').value;if(p===localStorage.getItem(key('pin'))){$('#lockView').classList.add('hidden');}else toast('PIN ไม่ถูกต้อง','error');}

function exportRows(){return state.tx.map(t=>({วันที่:t.date,เวลา:t.time||'',ประเภท:t.type==='income'?'รายรับ':'รายจ่าย',จำนวนเงิน:Number(t.amount)||0,หมวดหมู่:t.category||'',รายการ:t.title||'',แท็ก:(t.tags||[]).join(', '),หมายเหตุ:t.note||''}));}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCsv(){const rows=exportRows();const csv='\ufeff'+[Object.keys(rows[0]||{}).join(','),...rows.map(r=>Object.values(r).map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),'fintrack.csv');}
function exportExcel(){const ws=XLSX.utils.json_to_sheet(exportRows());const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Transactions');XLSX.writeFile(wb,'fintrack.xlsx');}
function exportPdf(){const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'portrait',unit:'pt'});pdf.setFont('helvetica');pdf.setFontSize(16);pdf.text('FinTrack Report',40,40);pdf.setFontSize(10);let y=65;exportRows().slice(0,35).forEach(r=>{pdf.text(`${r.วันที่} ${r.ประเภท} ${r.จำนวนเงิน} ${r.หมวดหมู่} ${r.รายการ}`.slice(0,105),40,y);y+=15});pdf.save('fintrack.pdf');}

function initEvents(){
  $$('.nav-item[data-nav]').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.nav))); $('#fabNav').addEventListener('click',()=>openTx('expense'));$$('[data-nav="transactions"]').forEach(b=>b.addEventListener('click',()=>openPage('transactions')));
  $$('.quick').forEach(b=>b.dataset.quickType&&b.addEventListener('click',()=>openTx(b.dataset.quickType)));$('#addTxTopBtn').addEventListener('click',()=>openTx());$('#openRecurringQuick').addEventListener('click',()=>openSimple('recurring'));
  $('#txForm').addEventListener('submit',saveTx);$('#deleteTxBtn').addEventListener('click',deleteTransaction);$$('.type-toggle button').forEach(b=>b.addEventListener('click',()=>{state.txType=b.dataset.type;$$('.type-toggle button').forEach(x=>x.classList.toggle('active',x===b));}));$('#txSearch').addEventListener('input',renderTransactions);$('#txTypeFilter').addEventListener('change',renderTransactions);$('#txMonthFilter').addEventListener('change',renderTransactions);
  $('#reportPeriod').addEventListener('change',renderReports);$('#exportCsvBtn').addEventListener('click',exportCsv);$('#exportExcelBtn').addEventListener('click',exportExcel);$('#exportPdfBtn').addEventListener('click',exportPdf);
  $('#addBudgetBtn').addEventListener('click',()=>openSimple('budget'));$('#addGoalBtn').addEventListener('click',()=>openSimple('goal'));$('#addCategoryBtn').addEventListener('click',()=>openSimple('category'));$('#addTagBtn').addEventListener('click',()=>openSimple('tag'));$('#simpleForm').addEventListener('submit',saveSimple);
  document.addEventListener('click',async e=>{const tx=e.target.closest('[data-edit-tx]');if(tx)openTx('expense',state.tx.find(t=>t.id===tx.dataset.editTx));const db=e.target.closest('[data-del-budget]');if(db&&confirm('ลบงบนี้?'))await deleteDoc(userDoc('budgets',db.dataset.delBudget));const dg=e.target.closest('[data-del-goal]');if(dg&&confirm('ลบเป้าหมายนี้?'))await deleteDoc(userDoc('goals',dg.dataset.delGoal));const ag=e.target.closest('[data-add-goal]');if(ag){const amt=prompt('เติมเงินจำนวนเท่าไร?');if(amt)await updateDoc(userDoc('goals',ag.dataset.addGoal),{saved:(state.goals.find(x=>x.id===ag.dataset.addGoal)?.saved||0)+Number(amt)});}const dc=e.target.closest('[data-del-cat]');if(dc&&confirm('ลบหมวดหมู่นี้?'))await deleteDoc(userDoc('categories',dc.dataset.delCat));const dt=e.target.closest('[data-del-tag]');if(dt&&confirm('ลบแท็กนี้?'))await deleteDoc(userDoc('tags',dt.dataset.delTag));});
  $$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#authSubmit').textContent=b.dataset.authTab==='login'?'เข้าสู่ระบบ':'สมัครสมาชิก';$('#authForm').dataset.mode=b.dataset.authTab;}));$('#authForm').dataset.mode='login';
  $('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;try{showLoading(true);if(e.currentTarget.dataset.mode==='register'){const c=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(c.user,{displayName:email.split('@')[0]});}else await signInWithEmailAndPassword(auth,email,password);}catch(err){$('#authError').textContent=err.message;$('#authError').classList.remove('hidden');}finally{showLoading(false);}});
  $('#resetPasswordBtn').addEventListener('click',async()=>{const e=$('#authEmail').value.trim();if(!e){toast('กรอกอีเมลก่อน','error');return}await sendPasswordResetEmail(auth,e);toast('ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว');});$('#logoutBtn').addEventListener('click',()=>signOut(auth));$('#lockNowBtn').addEventListener('click',lockApp);$('#setPinBtn').addEventListener('click',setPin);$('#pinEnabled').addEventListener('change',async e=>{await updateDoc(userDoc('settings','main'),{pinEnabled:e.target.checked});state.settings.pinEnabled=e.target.checked;if(e.target.checked&&!localStorage.getItem(key('pin')))await setPin();});$('#unlockBtn').addEventListener('click',unlock);$('#useAccountUnlockBtn').addEventListener('click',()=>signOut(auth));$('#enableNotificationsBtn').addEventListener('click',enableNotifications);$('#clearLocalBtn').addEventListener('click',async()=>{toast('Cache Firestore จะถูกจัดการโดย SDK; ใช้ล้าง site data ใน browser เมื่อต้องการล้างจริง','error')});
  $('#scanSlipBtn').addEventListener('click',()=>$('#scanModal').showModal());$('#closeScanBtn').addEventListener('click',()=>$('#scanModal').close());$('#receiptFile').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;$('#ocrPreview').innerHTML=`<img alt="preview" src="${URL.createObjectURL(file)}">`;$('#runOcrBtn').disabled=false;$('#runOcrBtn').onclick=()=>scanReceipt(file);});$('#useOcrBtn').addEventListener('click',()=>{const amount=$('#useOcrBtn').dataset.amount||'';const text=$('#useOcrBtn').dataset.text||'';$('#scanModal').close();openTx('expense');$('#txAmount').value=amount;$('#txTitle').value='สแกนสลิป';$('#txNote').value=text.slice(0,1500);});
  $('#dailyReminderTime').addEventListener('change',async e=>{await updateDoc(userDoc('settings','main'),{dailyReminderTime:e.target.value});});
  window.addEventListener('online',()=>$('#syncStatus').textContent='● Online');window.addEventListener('offline',()=>{$('#syncStatus').textContent='● Offline'});
}

function start(){initEvents();onAuthStateChanged(auth,async user=>{state.user=user;if(user){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');showLoading(true,'กำลังซิงก์ข้อมูล…');try{await loadAll();}catch(e){toast('โหลดข้อมูลไม่ได้: '+e.message,'error');}finally{showLoading(false);} }else{$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden');}});if('serviceWorker'in navigator)navigator.serviceWorker.register('firebase-messaging-sw.js').catch(()=>{});}
start();
